# Site settings
title: Anatoli Shatsila
email: anatoli.shatsila@student.uj.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Anatoli Shatsila
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anatolish00.github.io" # the base hostname & protocol for your site
github_username:  anatolish00

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
