# Site settings
title: Anatoli Shatsila
description: Mathematics PhD Student at Jagiellonian University
google_analytics:
email: anatoli.shatsila@doctoral.uj.edu.pl
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anatolish00.github.io" # the base hostname & protocol for your site
github_username:  anatolish00

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
